/**
 * Map ISO country codes to full country names in Portuguese
 */
const COUNTRY_NAMES: Record<string, string> = {
  AF: 'Afeganistão',
  AL: 'Albânia',
  DZ: 'Argélia',
  AD: 'Andorra',
  AO: 'Angola',
  AR: 'Argentina',
  AM: 'Armênia',
  AU: 'Austrália',
  AT: 'Áustria',
  AZ: 'Azerbaijão',
  BD: 'Bangladesh',
  BE: 'Bélgica',
  BO: 'Bolívia',
  BR: 'Brasil',
  BG: 'Bulgária',
  CA: 'Canadá',
  CL: 'Chile',
  CN: 'China',
  CO: 'Colômbia',
  CR: 'Costa Rica',
  HR: 'Croácia',
  CU: 'Cuba',
  CY: 'Chipre',
  CZ: 'República Tcheca',
  DK: 'Dinamarca',
  DO: 'República Dominicana',
  EC: 'Equador',
  EG: 'Egito',
  SV: 'El Salvador',
  EE: 'Estônia',
  FI: 'Finlândia',
  FR: 'França',
  DE: 'Alemanha',
  GH: 'Gana',
  GR: 'Grécia',
  GT: 'Guatemala',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungria',
  IS: 'Islândia',
  IN: 'Índia',
  ID: 'Indonésia',
  IR: 'Irã',
  IQ: 'Iraque',
  IE: 'Irlanda',
  IL: 'Israel',
  IT: 'Itália',
  JP: 'Japão',
  JO: 'Jordânia',
  KZ: 'Cazaquistão',
  KE: 'Quênia',
  KR: 'Coreia do Sul',
  KW: 'Kuwait',
  LV: 'Letônia',
  LB: 'Líbano',
  LT: 'Lituânia',
  LU: 'Luxemburgo',
  MY: 'Malásia',
  MX: 'México',
  MA: 'Marrocos',
  MZ: 'Moçambique',
  NL: 'Países Baixos',
  NZ: 'Nova Zelândia',
  NG: 'Nigéria',
  NO: 'Noruega',
  PK: 'Paquistão',
  PA: 'Panamá',
  PY: 'Paraguai',
  PE: 'Peru',
  PH: 'Filipinas',
  PL: 'Polônia',
  PT: 'Portugal',
  PR: 'Porto Rico',
  QA: 'Catar',
  RO: 'Romênia',
  RU: 'Rússia',
  SA: 'Arábia Saudita',
  RS: 'Sérvia',
  SG: 'Singapura',
  SK: 'Eslováquia',
  SI: 'Eslovênia',
  ZA: 'África do Sul',
  ES: 'Espanha',
  LK: 'Sri Lanka',
  SE: 'Suécia',
  CH: 'Suíça',
  TW: 'Taiwan',
  TH: 'Tailândia',
  TR: 'Turquia',
  UA: 'Ucrânia',
  AE: 'Emirados Árabes',
  GB: 'Reino Unido',
  US: 'Estados Unidos',
  UY: 'Uruguai',
  VE: 'Venezuela',
  VN: 'Vietnã',
};

export function getCountryName(code: string): string {
  return COUNTRY_NAMES[code.toUpperCase()] || code;
}
